# Generated by Django 5.1 on 2024-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_guerra', models.CharField(max_length=50)),
                ('graduacao', models.CharField(max_length=10)),
                ('antiguidade', models.CharField(max_length=4)),
            ],
        ),
    ]
