# Generated by Django 5.1 on 2024-09-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0002_rename_individuos_individuo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individuo',
            new_name='Militar',
        ),
    ]
