# Generated by Django 5.1 on 2024-10-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0005_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
