# Generated by Django 5.1 on 2024-10-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0007_alter_escala_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='mes_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
