# Generated by Django 5.1.3 on 2024-12-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0008_escala_mes_referencia_alter_escala_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='dias_da_semana',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
