# Generated by Django 5.1.3 on 2024-12-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0009_escala_dias_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='dias_da_semana',
            field=models.CharField(max_length=50),
        ),
    ]
