# Generated by Django 5.1.3 on 2024-12-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0010_alter_escala_dias_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escala_servico.militar'),
        ),
    ]
