# Generated by Django 5.1.3 on 2024-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0011_alter_escala_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='antiguidade',
            field=models.IntegerField(max_length=4),
        ),
    ]
