# Generated by Django 5.1 on 2024-12-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0012_alter_militar_antiguidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='antiguidade',
            field=models.IntegerField(),
        ),
    ]
