# Generated by Django 5.1.3 on 2025-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_servico', '0013_alter_militar_antiguidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
